run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - unconvert
    - unused
    - misspell
    - gosec
    - gosimple

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
