package content

// THE ACCEPTANCE SUITE FOR THE MIGRATION LADDER (nocx-lmb6v.2).
//
// Written from the acceptance criteria by somebody who did not write
// schema_migrate.go, which is the whole reason it is a separate bead
// (AGENTS.md rule 4). A migration that silently drops rows is the costliest
// defect this repo can ship once content.db stops being disposable, because it
// destroys the only copy of work a person cannot reproduce, and a test written
// by the implementation's author can only confirm that the code does what it
// was written to do.
//
// THE FIXTURES ARE REAL RELEASED SCHEMAS, and that is the criterion this file
// exists to satisfy. Both are the `schemaV1` constant lifted verbatim out of
// the tree at the commit where `const schemaVersion` held that number:
//
//	testdata/schema_v14.sql  ← a2fa7e3e, the last mainline commit at 14
//	testdata/schema_v13.sql  ← 1ccad4de, the last commit at 13
//
// Neither was generated by the current code. A fixture synthesised from the
// CURRENT schema would test the migration against the migration's own idea of
// the past, which is exactly the belief that is wrong on the day the migration
// is wrong: the past would agree with the present by construction, and the
// only thing the test could then discover is a typo. The two files carry their
// provenance in their own headers and are frozen.
//
// The two versions were chosen because they are the two sides of one boundary.
// 14 is the ladder's first rung, so it is the OLDEST database this build can
// carry forward; 13 is one below it, so it is the NEWEST database this build
// must refuse. A suite that tested either alone would not be testing a
// boundary at all.

import (
	"context"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ncruces/go-sqlite3"
	"github.com/ncruces/go-sqlite3/driver"
	_ "github.com/ncruces/go-sqlite3/vfs/adiantum"

	"github.com/shady2k/nocx/internal/log"
)

// ── the released fixtures ─────────────────────────────────────────────────

// releasedSchema reads one of the frozen scripts. It fails rather than skips
// when the file is missing: a suite that quietly stops testing the thing it is
// named after is worse than one that is red.
func releasedSchema(t *testing.T, version int) string {
	t.Helper()
	name := fmt.Sprintf("schema_v%d.sql", version)
	body, err := os.ReadFile(filepath.Join("testdata", name)) //nolint:gosec // a test-only path built from an int literal under this package's own testdata
	if err != nil {
		t.Fatalf("there is no released fixture for schema %d (%s): %v\n"+
			"Lift it verbatim out of the tree at the commit where `const schemaVersion` held %d, "+
			"and freeze it the way schema_v13.sql and schema_v14.sql are frozen. Do NOT generate it "+
			"from the current schema: a fixture the current code produced tests the migration "+
			"against the migration's own idea of the past.", version, name, err, version)
	}
	return string(body)
}

// aReleasedSchema14Database writes a database a shipped build of nocx would
// have written: the released DDL, rows in the tables the edge REBUILDS and in
// tables it never looks at, and the stamp.
//
// The values are deliberately distinctive rather than plausible. "Every row is
// still there" is a weaker claim than the one that matters — the edge rebuilds
// grant_scopes by copying it column by column into a new table, and a copy that
// pairs the right number of rows with the wrong values in them satisfies every
// count anybody could assert. So each string below is unique in the file, and
// assertTheRowsOfSchema14 reads them back as whole tuples.
// The creation-time pragmas precede the first table exactly as they do in
// Open. Omitting either would make this a schema-faithful but engine-different
// fixture: an upgraded file could then pass a parity test for the wrong reason.
func aReleasedSchema14Database(t *testing.T, path string) {
	t.Helper()
	rawExec(
		t, path,
		"PRAGMA auto_vacuum=INCREMENTAL",
		"PRAGMA journal_mode=WAL",
		releasedSchema(t, 14),
		// The released 14 startup sequence ran the api-run migration after
		// schemaV1, so this fixture carries those tables and their counter too.
		theTwoCounterEraAPIRunScript(t),
		`INSERT INTO api_run_schema (id, version) VALUES (1, 1)`,
		`INSERT INTO workspaces (id, name, colour, position, created_at, payload, digest)
			VALUES ('ws-fourteen', 'the workspace from before the upgrade', '#123456', 7, 1400, '{"kept":true}', 'digest-fourteen')`,
		`INSERT INTO tabs (id, workspace_id, name) VALUES ('tab-fourteen', 'ws-fourteen', 'the tab the user named')`,
		`INSERT INTO panes (id, tab_id, cwd, kind) VALUES ('pane-fourteen', 'tab-fourteen', '/srv/fourteen', 'local')`,
		`INSERT INTO environments (id, kind, first_seen) VALUES ('env-fourteen', 'local', 1400)`,
		`INSERT INTO environment_observations (id, environment_id, version, observed_at, criticality)
			VALUES (1, 'env-fourteen', 1, 1400, 'routine')`,
		`INSERT INTO entries
			(id, ingest_seq, client, digest, environment_id, pane_id, cwd, kind, source, intent, phase, status, submitted_at)
			VALUES ('entry-fourteen', 1, 'client-fourteen', 'digest-entry', 'env-fourteen', 'pane-fourteen',
			        '/srv/fourteen', 'shell', 'user', 'echo the command that must survive', 'closed', 'success', 1400)`,
		`INSERT INTO executions (id, entry_id, environment_obs_id) VALUES (1, 'entry-fourteen', 1)`,
		`INSERT INTO authority_grants (id, execution_id, version, issued_at, expires_at, policy)
			VALUES (1, 1, 1, 1400, 1460000, '{"kept":"yes"}')`,
		// The table the edge rebuilds. Two rows whose two text columns hold
		// values that are NOT interchangeable, so a copy that transposes them
		// is visible rather than merely suspected.
		`INSERT INTO grant_scopes (grant_id, resource_kind, resource_id) VALUES (1, 'session', 'session-fourteen')`,
		`INSERT INTO grant_scopes (grant_id, resource_kind, resource_id) VALUES (1, 'path', '/srv/fourteen/path')`,
		`INSERT INTO grant_effects (grant_id, effect) VALUES (1, 'observe')`,
		`UPDATE ledger_sequence SET next = 1 WHERE id = 1`,
		`PRAGMA user_version=14`,
	)
}

func TestReleasedSchema14FixtureIncludesTheAPIRunTablesAndCounter(t *testing.T) {
	path := filepath.Join(t.TempDir(), "content.db")
	aReleasedSchema14Database(t, path)

	for _, name := range []string{"api_run_schema", "api_runs", "api_run_artifacts", "api_run_artifact_chunks"} {
		if !aTableExists(t, path, name) {
			t.Fatalf("released schema 14 fixture has no %s table — a real schema 14 build created every api-run table before stamping the file", name)
		}
	}
	if got := rawCount(t, path, `SELECT version FROM api_run_schema WHERE id = 1`); got != 1 {
		t.Fatalf("released schema 14 fixture api-run counter = %d, want 1 — the fixture must carry the counter its build wrote", got)
	}
}

func TestAStampedSchema14DatabaseWithAnotherShapeIsRefusedBeforeMigration(t *testing.T) {
	path := filepath.Join(t.TempDir(), "content.db")
	aReleasedSchema14Database(t, path)
	rawExec(t, path,
		`DROP TABLE entries`,
		`PRAGMA user_version=14`,
	)

	_, err := Open(context.Background(), Config{
		Path: path, Key: schemaTestKey(), Budget: testBudgetInternal(), Logger: log.NewSlogAdapter(nil),
	})
	if err == nil {
		t.Fatal("Open accepted a database stamped schema 14 whose tables have a different shape")
	}
	if !strings.Contains(err.Error(), "missing") || !strings.Contains(err.Error(), `table "entries"`) {
		t.Fatalf("shape refusal reads %q; it must name the missing entries table", err)
	}
	if got := rawUserVersion(t, path); got != 14 {
		t.Fatalf("user_version = %d after shape refusal, want 14 — the ladder migrated a file before checking what its stamp described", got)
	}
	if scopeErr := rawTry(t, path, aContentScope); scopeErr == nil {
		t.Fatal("the malformed schema 14 file was migrated before its shape was refused")
	}
}

// assertTheRowsOfSchema14 is "its rows are present AND CORRECT afterwards",
// spelled out. Every assertion is a whole tuple read back from the raw file,
// because the failure this suite exists to catch is not an empty table — an
// empty table is loud — but a table with the right shape and the wrong
// contents.
func assertTheRowsOfSchema14(t *testing.T, path string) {
	t.Helper()
	for _, want := range []struct {
		what  string
		query string
		rows  []string
	}{
		{
			"the table the edge rebuilds, as whole tuples",
			`SELECT grant_id || '|' || resource_kind || '|' || resource_id
				FROM grant_scopes ORDER BY resource_kind`,
			[]string{"1|path|/srv/fourteen/path", "1|session|session-fourteen"},
		},
		{
			"the workspace, every column of it",
			`SELECT id || '|' || name || '|' || colour || '|' || position || '|' || created_at || '|' || payload || '|' || digest
				FROM workspaces WHERE id = 'ws-fourteen'`,
			[]string{"ws-fourteen|the workspace from before the upgrade|#123456|7|1400|{\"kept\":true}|digest-fourteen"},
		},
		{
			"the tab the user named, still attached to its workspace",
			`SELECT id || '|' || workspace_id || '|' || name FROM tabs`,
			[]string{"tab-fourteen|ws-fourteen|the tab the user named"},
		},
		{
			"the pane and its working directory",
			`SELECT id || '|' || tab_id || '|' || cwd || '|' || kind FROM panes`,
			[]string{"pane-fourteen|tab-fourteen|/srv/fourteen|local"},
		},
		{
			"the recorded command",
			`SELECT id || '|' || intent || '|' || kind || '|' || source || '|' || phase || '|' || status
				FROM entries WHERE id = 'entry-fourteen'`,
			[]string{"entry-fourteen|echo the command that must survive|shell|user|closed|success"},
		},
		{
			"the grant the scopes hang off",
			`SELECT id || '|' || execution_id || '|' || policy FROM authority_grants`,
			[]string{"1|1|{\"kept\":\"yes\"}"},
		},
		{
			// A counter that is not carried forward re-issues sequence
			// numbers that are already on rows, which is a corruption no row
			// count can see.
			"the ledger's own counter",
			`SELECT next FROM ledger_sequence WHERE id = 1`,
			[]string{"1"},
		},
	} {
		got := rawStrings(t, path, want.query)
		if len(got) != len(want.rows) {
			t.Fatalf("%s: read %d rows %q, want %d %q", want.what, len(got), got, len(want.rows), want.rows)
		}
		for i := range got {
			if got[i] != want.rows[i] {
				t.Fatalf("%s: row %d is %q, want %q — the rows came through the version change altered", want.what, i, got[i], want.rows[i])
			}
		}
	}
}

// rawStrings reads a one-column query off the encrypted file without going
// through Open, so the rows can be asked of a database the store REFUSED as
// well as one it accepted.
func rawStrings(t *testing.T, path, query string) []string {
	t.Helper()
	conn, done := rawConn(t, path)
	defer done()
	rows, err := conn.QueryContext(context.Background(), query)
	if err != nil {
		t.Fatalf("query %q: %v", query, err)
	}
	defer func() { _ = rows.Close() }()
	var out []string
	for rows.Next() {
		var s string
		if err := rows.Scan(&s); err != nil {
			t.Fatalf("scan %q: %v", query, err)
		}
		out = append(out, s)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("query %q: %v", query, err)
	}
	return out
}

// rawTryWithForeignKeys is rawTry with enforcement ON, which is how a
// CONSTRAINT that survived a table rebuild is asserted. The rebuild drops the
// old grant_scopes and renames a new one over it; a new table that forgot the
// reference to authority_grants would keep every row, pass every count, and
// silently stop enforcing the thing the column exists for.
func rawTryWithForeignKeys(t *testing.T, path, statement string) error {
	t.Helper()
	keyHex := hex.EncodeToString(schemaTestKey())
	db, err := driver.Open("file:"+path+"?vfs=adiantum", func(c *sqlite3.Conn) error {
		return c.Exec("PRAGMA hexkey='" + keyHex + "'")
	})
	if err != nil {
		t.Fatalf("raw open: %v", err)
	}
	defer func() { _ = db.Close() }()
	if _, pragmaErr := db.ExecContext(context.Background(), "PRAGMA foreign_keys=ON"); pragmaErr != nil {
		t.Fatalf("enable foreign keys: %v", pragmaErr)
	}
	_, err = db.ExecContext(context.Background(), statement)
	return err
}

// ── the happy path, on a real released database ───────────────────────────

// A DATABASE WRITTEN BY THE LAST RELEASED SCHEMA OPENS, AND ITS ROWS ARE STILL
// THERE AND STILL SAY WHAT THEY SAID.
//
// This is the criterion's headline and the paired positive that every refusal
// in this file is measured against: on an ordinary database, the thing
// succeeds. AGENTS.md records an epic whose every failure path was tested and
// where nothing asserted the feature was obtainable on a normal machine, where
// it never was — so the positive is not a courtesy, it is the assertion that
// makes the negatives mean anything.
func TestAReleasedSchema14DatabaseMigratesForwardWithItsRowsUnaltered(t *testing.T) {
	path := filepath.Join(t.TempDir(), "content.db")
	aReleasedSchema14Database(t, path)

	db, err := Open(context.Background(), Config{
		Path: path, Key: schemaTestKey(), Budget: testBudgetInternal(), Logger: log.NewSlogAdapter(nil),
	})
	if err != nil {
		t.Fatalf("Open over a released schema 14 database: %v — the last shipped shape must migrate, not refuse", err)
	}
	t.Cleanup(func() { _ = db.Close() })

	if got := rawUserVersion(t, path); got != schemaVersion {
		t.Fatalf("user_version = %d, want %d", got, schemaVersion)
	}
	assertTheRowsOfSchema14(t, path)

	// The edge did what it was for: the widened CHECK admits the kinds 15
	// added, and still refuses one no version ever defined. A rebuild that
	// dropped the constraint altogether would pass the first half alone.
	if scopeErr := rawTry(t, path, aContentScope); scopeErr != nil {
		t.Fatalf("a 'content' scope is refused after the migration: %v — the edge did not widen the CHECK", scopeErr)
	}
	if kindErr := rawTry(t, path,
		`INSERT INTO grant_scopes (grant_id, resource_kind, resource_id) VALUES (1, 'not-a-kind', 'x')`); kindErr == nil {
		t.Fatal("the rebuilt grant_scopes accepted a resource kind no schema ever defined — the widening dropped the CHECK instead of widening it")
	}

	// And the constraints that are not the point of the edge survived it too.
	if fkErr := rawTryWithForeignKeys(t, path,
		`INSERT INTO grant_scopes (grant_id, resource_kind, resource_id) VALUES (99, 'session', 'orphan')`); fkErr == nil {
		t.Fatal("the rebuilt grant_scopes accepted a scope pointing at a grant that does not exist — the table rebuild lost its foreign key")
	}
	if dupErr := rawTry(t, path,
		`INSERT INTO grant_scopes (grant_id, resource_kind, resource_id) VALUES (1, 'session', 'session-fourteen')`); dupErr == nil {
		t.Fatal("the rebuilt grant_scopes accepted a duplicate of a row it already holds — the table rebuild lost its primary key")
	}

	// AND THE STORE WORKS ON THE MIGRATED FILE. A database that opens and
	// then fails every write is the shape a stamp alone cannot rule out.
	if _, recordErr := db.Ledger().RecordCompleted(context.Background(), aRecordedCommand("echo after the upgrade")); recordErr != nil {
		t.Fatalf("RecordCompleted on the migrated database: %v", recordErr)
	}
	page, err := db.Ledger().QueryEntries(context.Background(), LedgerQuery{Scope: ScopeEverywhere, Limit: 50})
	if err != nil {
		t.Fatalf("QueryEntries after the migration: %v", err)
	}
	var intents []string
	for _, e := range page.Entries {
		intents = append(intents, e.Intent)
	}
	if !slicesContain(intents, "echo the command that must survive") {
		t.Fatalf("the command recorded under schema 14 is not readable through the store: %q", intents)
	}
	if !slicesContain(intents, "echo after the upgrade") {
		t.Fatalf("the command recorded after the migration is not readable: %q", intents)
	}
}

func slicesContain(hay []string, needle string) bool {
	for _, s := range hay {
		if s == needle {
			return true
		}
	}
	return false
}

// ── the floor, and that it is derived rather than written down ────────────

// THE NEWEST DATABASE THIS BUILD MUST REFUSE is one below the ladder's first
// rung, and it is refused with every row left where it was.
//
// The version is not spelled 13 in the assertions: it is computed from
// schemaLadder, so the day somebody retires the 14→15 rung this test starts
// asking about the new floor instead of going quietly green on an old one.
func TestAReleasedDatabaseOneBelowTheFirstRungIsRefusedWithEveryRowIntact(t *testing.T) {
	// The day the first rung moves, this asks for the released shape below the
	// NEW floor and goes red naming the file it needs, rather than skipping. A
	// boundary test that disables itself when the boundary moves is the one
	// failure mode it cannot afford: it would stay green for exactly as long as
	// the thing it guards was unguarded.
	floor := schemaLadder[0].from
	path := filepath.Join(t.TempDir(), "content.db")
	rawExec(t, path,
		releasedSchema(t, floor-1),
		`INSERT INTO workspaces (id, name, created_at) VALUES ('ws-thirteen', 'the workspace nobody may destroy', 1300)`,
		`INSERT INTO tabs (id, workspace_id, name) VALUES ('tab-thirteen', 'ws-thirteen', 'a tab from schema 13')`,
		`PRAGMA user_version=13`,
	)

	_, err := Open(context.Background(), Config{
		Path: path, Key: schemaTestKey(), Budget: testBudgetInternal(), Logger: log.NewSlogAdapter(nil),
	})
	if err == nil {
		t.Fatalf("Open accepted a schema %d database, which is below the ladder's first rung (%d)", floor-1, floor)
	}
	// The refusal is what a person reads in Settings, so it has to name the
	// numbers rather than merely report a mismatch.
	for _, want := range []string{
		fmt.Sprintf("%d", floor-1),
		fmt.Sprintf("%d", schemaVersion),
		fmt.Sprintf("%d", floor),
		"no rows were discarded",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("the refusal reads %q; it must contain %q", err.Error(), want)
		}
	}

	// NEVER REBUILT. This is the case the old code dropped every table for,
	// and the table NAMES here are entirely familiar to this build — which is
	// why the unknown-table gate that used to stand in front of the rebuild
	// could not have saved this file.
	if got := rawUserVersion(t, path); got != floor-1 {
		t.Fatalf("user_version = %d after the refusal, want %d — a refusal that restamps invites the next open to migrate a shape it never checked", got, floor-1)
	}
	if n := rawCount(t, path, `SELECT count(*) FROM workspaces`); n != 1 {
		t.Fatalf("workspaces holds %d rows after the refusal, want 1 — the refusal destroyed rows", n)
	}
	if rows := rawStrings(t, path, `SELECT name FROM tabs`); len(rows) != 1 || rows[0] != "a tab from schema 13" {
		t.Fatalf("tabs after the refusal = %q, want the row untouched", rows)
	}
	// Open cannot promise the bytes — it sets journal_mode before it reaches
	// the decision — so this asserts what it can: the file the store refused
	// still has every table schema 13 gave it, none added and none dropped.
	if n := rawCount(t, path,
		`SELECT count(*) FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'`); n == 0 {
		t.Fatal("the refused database has no tables left at all")
	}
}

// THE FLOOR IS DERIVED FROM THE LADDER, NOT WRITTEN DOWN, and the only way to
// show that is to move the ladder and watch the floor move with it.
//
// The same file, the same function, two different ladders. Under the shipped
// chain it is below the first rung and is refused; under a chain with one more
// rung beneath it, it is simply an old database with a step, and the refusal
// does not happen. If the floor were a constant in the code, the second half
// would refuse too and this test would be the only thing that noticed.
func TestTheFloorMovesWithTheLadderRatherThanBeingAConstant(t *testing.T) {
	build := func(t *testing.T) string {
		t.Helper()
		path := filepath.Join(t.TempDir(), "content.db")
		rawExec(t, path,
			releasedSchema(t, 13),
			`INSERT INTO workspaces (id, name, created_at) VALUES ('ws-thirteen', 'kept', 1300)`,
			`PRAGMA user_version=13`,
		)
		return path
	}

	// Under the shipped ladder: refused, and the message names the ladder's
	// own first rung.
	shipped := build(t)
	conn, done := rawConn(t, shipped)
	shippedErr := migrateSchema(context.Background(), conn, schemaLadder, log.NewSlogAdapter(nil))
	done()
	if shippedErr == nil {
		t.Fatalf("migrateSchema accepted a schema 13 file under a ladder starting at %d", schemaLadder[0].from)
	}
	if !strings.Contains(shippedErr.Error(), fmt.Sprintf("starts at schema %d", schemaLadder[0].from)) {
		t.Fatalf("the refusal reads %q; it must name the ladder's first rung (%d) rather than a hard-coded floor",
			shippedErr.Error(), schemaLadder[0].from)
	}

	// Under a ladder with a rung beneath that one: not refused. The step is a
	// real ALTER — schema 13's `entries` has no `source` column, which is the
	// actual difference between the two released shapes — so this is a chain
	// that could genuinely exist, not a no-op that proves nothing.
	lowered := build(t)
	longer := append([]migrationStep{{
		from: 13, to: 14,
		apply: func(ctx context.Context, tx *sql.Tx) error {
			_, err := tx.ExecContext(ctx,
				`ALTER TABLE entries ADD COLUMN source TEXT NOT NULL DEFAULT 'user'`)
			return err
		},
	}}, schemaLadder...)
	conn, done = rawConn(t, lowered)
	loweredErr := migrateSchema(context.Background(), conn, longer, log.NewSlogAdapter(nil))
	done()
	if loweredErr != nil {
		t.Fatalf("migrateSchema refused a schema 13 file under a ladder that starts at 13: %v — the floor is a constant, not schemaLadder[0].from", loweredErr)
	}
	if got := rawUserVersion(t, lowered); got != schemaVersion {
		t.Fatalf("user_version = %d after walking the longer ladder, want %d", got, schemaVersion)
	}
	if n := rawCount(t, lowered, `SELECT count(*) FROM workspaces`); n != 1 {
		t.Fatalf("workspaces holds %d rows after walking two rungs, want 1", n)
	}
}

// ── the failure paths, each with the positive that gives it meaning ───────

// A BUILD THAT CARRIES NO STEPS AT ALL refuses an old database rather than
// leaving it at whatever version it found. Paired, in the same test, with the
// shipped ladder on the same file succeeding — which is the only thing that
// distinguishes "refuses when it has no steps" from "refuses".
func TestAnEmptyLadderRefusesRatherThanOpeningAnOldDatabase(t *testing.T) {
	path := filepath.Join(t.TempDir(), "content.db")
	aReleasedSchema14Database(t, path)

	conn, done := rawConn(t, path)
	err := migrateSchema(context.Background(), conn, nil, log.NewSlogAdapter(nil))
	done()
	if err == nil {
		t.Fatal("migrateSchema opened a schema 14 database with no migration steps at all")
	}
	if !strings.Contains(err.Error(), "no rows were discarded") {
		t.Fatalf("the refusal reads %q; a refusal must say the rows are safe", err.Error())
	}
	if got := rawUserVersion(t, path); got != 14 {
		t.Fatalf("user_version = %d after the refusal, want 14", got)
	}
	assertTheRowsOfSchema14(t, path)

	// AND ON AN ORDINARY BUILD IT SUCCEEDS: the same file, the shipped
	// ladder.
	conn, done = rawConn(t, path)
	err = migrateSchema(context.Background(), conn, schemaLadder, log.NewSlogAdapter(nil))
	done()
	if err != nil {
		t.Fatalf("migrateSchema refused the same file under the shipped ladder: %v", err)
	}
	if got := rawUserVersion(t, path); got != schemaVersion {
		t.Fatalf("user_version = %d, want %d", got, schemaVersion)
	}
	assertTheRowsOfSchema14(t, path)
}

// THE COMPENSATION FOR SUSPENDING FOREIGN KEYS IS ITSELF ASSERTED.
//
// The walk runs with `PRAGMA foreign_keys=OFF`, because SQLite's documented
// table-rebuild procedure cannot run with enforcement on. What replaces the
// enforcement for the duration is one `PRAGMA foreign_key_check` inside each
// step's transaction — so that check is the only thing standing between a
// badly written step and a committed database the engine would never have
// accepted. If it silently reported nothing, every existing test would stay
// green and the guarantee would be gone.
//
// A step that leaves a dangling reference must therefore fail, and the file
// must be left at the version it started at with the dangling row rolled back
// out of it. Paired with the same step minus the dangling row, which must
// commit — otherwise this would pass against a check that rejects everything.
func TestAStepThatLeavesADanglingReferenceIsRefusedAndRolledBack(t *testing.T) {
	dangling := filepath.Join(t.TempDir(), "content.db")
	aReleasedSchema14Database(t, dangling)

	conn, done := rawConn(t, dangling)
	err := migrateSchema(context.Background(), conn, theLadderWithThisEdgeSwapped(migrationStep{
		from: 14, to: 15,
		apply: func(ctx context.Context, tx *sql.Tx) error {
			if err := migrateGrantScopeKinds14to15(ctx, tx); err != nil {
				return err
			}
			// A scope pointing at a grant that does not exist. With
			// enforcement suspended for the walk this INSERT succeeds; only
			// the foreign-key check can catch it.
			_, insertErr := tx.ExecContext(ctx,
				`INSERT INTO grant_scopes (grant_id, resource_kind, resource_id) VALUES (4242, 'session', 'dangling')`)
			return insertErr
		},
	}), log.NewSlogAdapter(nil))
	done()
	if err == nil {
		t.Fatal("a step that left a dangling foreign key committed — the check that stands in for the suspended enforcement is not working")
	}
	if !strings.Contains(err.Error(), "foreign key") {
		t.Fatalf("the failure reads %q; it must name the foreign key violation so the step's author can find it", err.Error())
	}
	if got := rawUserVersion(t, dangling); got != 14 {
		t.Fatalf("user_version = %d after the rejected step, want 14", got)
	}
	if n := rawCount(t, dangling, `SELECT count(*) FROM grant_scopes`); n != 2 {
		t.Fatalf("grant_scopes holds %d rows after the rejected step, want the 2 it started with — the dangling row survived its own rollback", n)
	}
	assertTheRowsOfSchema14(t, dangling)

	// AND THE SAME STEP WITHOUT THE DANGLING ROW COMMITS. Without this the
	// test above is satisfied by a check that fails every migration.
	clean := filepath.Join(t.TempDir(), "content.db")
	aReleasedSchema14Database(t, clean)
	conn, done = rawConn(t, clean)
	err = migrateSchema(context.Background(), conn, theLadderWithThisEdgeSwapped(migrationStep{
		from: 14, to: 15,
		apply: func(ctx context.Context, tx *sql.Tx) error {
			if edgeErr := migrateGrantScopeKinds14to15(ctx, tx); edgeErr != nil {
				return edgeErr
			}
			_, insertErr := tx.ExecContext(ctx,
				`INSERT INTO grant_scopes (grant_id, resource_kind, resource_id) VALUES (1, 'content', 'note/kept')`)
			return insertErr
		},
	}), log.NewSlogAdapter(nil))
	done()
	if err != nil {
		t.Fatalf("a step whose references are all intact was refused: %v", err)
	}
	if got := rawUserVersion(t, clean); got != schemaVersion {
		t.Fatalf("user_version = %d, want %d", got, schemaVersion)
	}
	if n := rawCount(t, clean, `SELECT count(*) FROM grant_scopes`); n != 3 {
		t.Fatalf("grant_scopes holds %d rows, want 3", n)
	}
}

// A FAILURE IN THE MIDDLE OF AN EDGE LEAVES THE FILE BYTE FOR BYTE AS IT WAS.
//
// The acceptance criterion asks for byte-intact, and on this path it is
// obtainable, which is why it is asserted as bytes rather than as rows: the
// injected failure is given a connection that has had no `journal_mode` set on
// it, so nothing but the edge itself writes to the file, and a rolled-back
// transaction restores the pages it touched. (Through `Open` the same claim is
// only about rows — Open puts the file into WAL before it reaches the
// decision, and closing that handle checkpoints. That distinction is the
// implementation's and it is stated in schema_migrate.go; this test pins the
// stronger half where the stronger half is real.)
//
// The failure is injected AFTER the real edge's own DDL has run, so what is
// rolled back is a table that was genuinely dropped and recreated, not a
// transaction that never did anything.
func TestAFailureMidEdgeLeavesTheFileByteForByteAsItWas(t *testing.T) {
	path := filepath.Join(t.TempDir(), "content.db")
	aReleasedSchema14Database(t, path)
	before := fingerprint(t, path)

	boom := errors.New("the edge failed half way through")
	conn, done := rawConn(t, path)
	err := migrateSchema(context.Background(), conn, theLadderWithThisEdgeSwapped(migrationStep{
		from: 14, to: 15,
		apply: func(ctx context.Context, tx *sql.Tx) error {
			if err := migrateGrantScopeKinds14to15(ctx, tx); err != nil {
				return err
			}
			return boom
		},
	}), log.NewSlogAdapter(nil))
	done()
	if !errors.Is(err, boom) {
		t.Fatalf("migrateSchema returned %v, want the injected failure", err)
	}

	after := fingerprint(t, path)
	if after.size != before.size || after.sum != before.sum {
		t.Fatalf("the file changed across a failed edge: %d bytes / %s became %d bytes / %s — a rolled-back edge left something behind",
			before.size, before.sum, after.size, after.sum)
	}
	assertTheRowsOfSchema14(t, path)
	if scopeErr := rawTry(t, path, aContentScope); scopeErr == nil {
		t.Fatal("a 'content' scope inserted after the edge failed — half the edge survived its own rollback")
	}

	// AND THE NEXT START COMPLETES IT, which is the difference between a
	// database that is safe and one that is stuck.
	db, err := Open(context.Background(), Config{
		Path: path, Key: schemaTestKey(), Budget: testBudgetInternal(), Logger: log.NewSlogAdapter(nil),
	})
	if err != nil {
		t.Fatalf("Open after the failed edge: %v — the next start must complete it or refuse, and refusing a file it can migrate is neither", err)
	}
	t.Cleanup(func() { _ = db.Close() })
	if got := rawUserVersion(t, path); got != schemaVersion {
		t.Fatalf("user_version = %d after the retry, want %d", got, schemaVersion)
	}
	assertTheRowsOfSchema14(t, path)
	if err := rawTry(t, path, aContentScope); err != nil {
		t.Fatalf("a 'content' scope is still refused after the retry: %v", err)
	}
}

// THE OTHER DIRECTION, PAIRED IN ONE TEST. A database written by a NEWER
// schema is refused without a byte moving; a database written by THIS schema
// opens. Both halves run against the same function on files that differ only
// in their stamp, which is what makes the refusal a decision about direction
// rather than about the file.
func TestANewerDatabaseIsRefusedAndACurrentOneOpens(t *testing.T) {
	newer := filepath.Join(t.TempDir(), "content.db")
	aReleasedSchema14Database(t, newer)
	rawExec(t, newer, fmt.Sprintf("PRAGMA user_version=%d", schemaVersion+1))
	before := fingerprint(t, newer)

	conn, done := rawConn(t, newer)
	err := migrateSchema(context.Background(), conn, schemaLadder, log.NewSlogAdapter(nil))
	done()
	if err == nil {
		t.Fatalf("migrateSchema accepted a database written by schema %d", schemaVersion+1)
	}
	if !strings.Contains(err.Error(), fmt.Sprintf("update nocx to a build that understands schema %d", schemaVersion+1)) {
		t.Fatalf("the refusal reads %q; it must tell the user which build they need", err.Error())
	}
	after := fingerprint(t, newer)
	if after.size != before.size || after.sum != before.sum {
		t.Fatal("the refusal modified the file — an older build must not touch a database a newer one wrote")
	}
	if got := rawUserVersion(t, newer); got != schemaVersion+1 {
		t.Fatalf("user_version = %d after the refusal, want %d", got, schemaVersion+1)
	}

	// AND A DATABASE AT THIS EXACT VERSION OPENS, untouched, with no
	// migration run over it.
	current := aFreshDatabase(t)
	rawExec(t, current, fmt.Sprintf("PRAGMA user_version=%d", schemaVersion))
	stable := fingerprint(t, current)
	conn, done = rawConn(t, current)
	err = migrateSchema(context.Background(), conn, schemaLadder, log.NewSlogAdapter(nil))
	done()
	if err != nil {
		t.Fatalf("migrateSchema refused a database at the current version: %v", err)
	}
	if got := fingerprint(t, current); got.sum != stable.sum {
		t.Fatal("a database already at the current version was written to — the equal case must be a no-op")
	}
}
