// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BackendResolution is the result of one coordinator discovery attempt.
 * Token is returned only to the renderer through this binding; it is never
 * written to logs, argv or the spawned daemon's environment.
 */
export class BackendResolution {
    "ok": boolean;
    "host": string;
    "port": number;
    "token": string;
    "kind": string;
    "message": string;
    "remedy": string;

    /** Creates a new BackendResolution instance. */
    constructor($$source: Partial<BackendResolution> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("remedy" in $$source)) {
            this["remedy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackendResolution instance from a string or object.
     */
    static createFrom($$source: any = {}): BackendResolution {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackendResolution($$parsedSource as Partial<BackendResolution>);
    }
}
