// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsApp is the bound service (v3) the frontend reaches over the Wails
 * runtime.
 * 
 * IT IS A WINDOW AND A LAUNCHER, and no longer a backend (design D3). The
 * sessions, the vault, the stores and the WebSocket live in nocx-server, a
 * process of their own that outlives this window; what this struct holds is
 * how to reach that process and what to tell the person when reaching it
 * went badly.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "./internal/update/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyUpdate applies a previously checked update. No arguments —
 * the update info is already verified and held in window state.
 */
export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByName("main.WailsApp.ApplyUpdate");
}

/**
 * CheckForUpdate fetches and verifies the signed release manifest.
 * Returns an update description if a newer version is available,
 * or null when already current or on a dev build.
 */
export function CheckForUpdate(): $CancellablePromise<update$0.UpdateInfo | null> {
    return $Call.ByName("main.WailsApp.CheckForUpdate").then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUpdateState returns the updater state for the UI notice.
 * "pending" means an update was applied and is waiting for a restart;
 * empty string means nothing in flight.
 */
export function GetUpdateState(): $CancellablePromise<string> {
    return $Call.ByName("main.WailsApp.GetUpdateState");
}

/**
 * HostBadge sets the dock badge count; 0 clears it. The Wails host does not
 * implement it (nocx-3a40), and it says so loudly rather than pretending to
 * have delivered.
 */
export function HostBadge(count: number): $CancellablePromise<void> {
    return $Call.ByName("main.WailsApp.HostBadge", count);
}

/**
 * HostBanner presents one desktop notification banner. Title and body reach
 * the OS verbatim; sessionId rides in the notification's payload and comes
 * back on a click.
 */
export function HostBanner(title: string, body: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByName("main.WailsApp.HostBanner", title, body, sessionID);
}

/**
 * HostBounce requests the attention bounce. Same absence as HostBadge, same
 * loud error.
 */
export function HostBounce(): $CancellablePromise<void> {
    return $Call.ByName("main.WailsApp.HostBounce");
}

/**
 * HostFocusWindow brings this window to the front. The coordinator asks for
 * it when it has decided a click should land here; the shell only raises.
 */
export function HostFocusWindow(): $CancellablePromise<void> {
    return $Call.ByName("main.WailsApp.HostFocusWindow");
}

/**
 * HostOpenDirectory is the same v3 open dialog restricted to directories:
 * CanChooseFiles(false) is what makes a file unselectable, so a caller
 * expecting a folder cannot be handed one. Same cancellation contract as
 * HostOpenFile.
 */
export function HostOpenDirectory(): $CancellablePromise<string> {
    return $Call.ByName("main.WailsApp.HostOpenDirectory");
}

/**
 * HostOpenFile opens the platform file picker and returns the chosen ABSOLUTE
 * path, or "" when the person cancelled.
 * 
 * It cannot be dismissed from here — the v3 open dialog has no cancel handle
 * once shown — so the call returns only when the person acts. That is the
 * contract transport.DialogService has always documented for a
 * non-cooperative adapter, and the coordinator's capacity-one waiting gate is
 * what keeps a second picker from stacking meanwhile.
 */
export function HostOpenFile(): $CancellablePromise<string> {
    return $Call.ByName("main.WailsApp.HostOpenFile");
}

/**
 * HostOpenUrl opens a URL in the system browser. The coordinator has already
 * refused anything that is not an http(s) URL with a host (ws_openurl.go);
 * this side adds no second gate, because a second answer to one question is
 * how the two drift apart.
 */
export function HostOpenUrl(url: string): $CancellablePromise<void> {
    return $Call.ByName("main.WailsApp.HostOpenUrl", url);
}

/**
 * Log logs a message from the frontend.
 * 
 * It reaches this process's stderr rather than the backend's log file: the
 * renderer is this window's, and the file belongs to the daemon now.
 */
export function Log(message: string): $CancellablePromise<void> {
    return $Call.ByName("main.WailsApp.Log", message);
}

/**
 * LogFilePath reports where the backend log file lives. "" means
 * unavailable, which is the honest answer while the log belongs to a process
 * this one only talks to over a socket: the discovery handshake carries four
 * facts and this is not one of them. Restoring it is the client host's
 * (design D3, A1.2) — it needs a control-plane call, not a guess at a path.
 */
export function LogFilePath(): $CancellablePromise<string> {
    return $Call.ByName("main.WailsApp.LogFilePath");
}

/**
 * ReportHealthy signals that the frontend is running correctly.
 * Called once the initial tab's renderer mounted and its PTY session
 * opened (§7.5). Only then does the updater finalise a pending update.
 * 
 * It certifies a PAIR: the updater asks the launch probe which coordinator
 * answered this window, and finalises only when that backend is the version
 * this update installed (D4). A mixed pair — the old daemon surviving the
 * bundle swap — is refused here and the rollback journal is left intact.
 */
export function ReportHealthy(): $CancellablePromise<void> {
    return $Call.ByName("main.WailsApp.ReportHealthy");
}

/**
 * ResolveBackend runs one discovery attempt. A startup failure is reported
 * once before a later call retries, so the renderer sees the original reason
 * without turning startup into a second launch.
 */
export function ResolveBackend(): $CancellablePromise<$models.BackendResolution> {
    return $Call.ByName("main.WailsApp.ResolveBackend").then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = update$0.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.BackendResolution.createFrom;
