// Command framebytes runs the §8.1 measurement: what a backend-owned screen
// costs to deliver as frames, against the raw PTY bytes nocx ships today.
//
//	framebytes -corpus ../emulator/corpus -out results/tables.md
//
// It writes the report's tables and prints them; REPORT.md carries the prose.
package main

import (
	"bytes"
	"compress/flate"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	fb "nocx.internal/spikes/framebytes"
)

func main() {
	corpus := flag.String("corpus", "../emulator/corpus", "directory of recorded JSONL captures")
	fps := flag.String("fps", "5,15,30,60,120,every", "frame rates to sweep; 'every' means one frame per write")
	heroSeconds := flag.Float64("hero", 5, "seconds of the generated hero capture; 0 disables it")
	out := flag.String("out", "results/tables.md", "where to write the generated tables")
	flag.Parse()

	var b strings.Builder
	fmt.Fprintf(&b, "<!-- generated by: cd .internal/spikes/framebytes && go run ./cmd/framebytes -->\n")
	fmt.Fprintf(&b, "<!-- %s; %s; corpus=%s -->\n\n", runtime.Version(), runtime.GOOS+"/"+runtime.GOARCH, *corpus)

	caps, err := fb.LoadCorpus(*corpus)
	if err != nil {
		fmt.Fprintln(os.Stderr, "load corpus:", err)
		os.Exit(1)
	}
	if *heroSeconds > 0 {
		caps = append(caps, fb.Hero(*heroSeconds))
	}

	configs := parseConfigs(*fps)

	fmt.Fprintf(&b, "## Captures\n\n")
	fmt.Fprintf(&b, "| capture | geometry | writes | duration | RAW bytes |\n|---|---|---|---|---|\n")
	for _, c := range caps {
		fmt.Fprintf(&b, "| %s | %d×%d | %d | %d ms | %d |\n",
			c.Name, c.Cols, c.Rows, len(c.Chunks), c.DurationMs(), c.RawBytes())
	}
	fmt.Fprintln(&b)

	for _, c := range caps {
		if c.Note != "" {
			fmt.Fprintf(&b, "%s: %s. SHA-256 of its byte stream: `%s`.\n\n", c.Name, c.Note, c.Digest())
		}
		var rows []*fb.Metrics
		for _, cfg := range configs {
			rows = append(rows, fb.Measure(c, cfg))
		}
		fmt.Fprintf(&b, "## %s\n\n", c.Name)
		writeTable(&b, rows)
		if c.Name == "hero" {
			writeHeroRates(&b, rows)
		}
		fmt.Fprintln(&b)
	}

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	writeCompression(&b, caps)
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Print(b.String())
	fmt.Printf("\nwrote %s\n", *out)
}

func parseConfigs(s string) []fb.Config {
	var out []fb.Config
	for _, part := range strings.Split(s, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		if part == "every" || part == "0" {
			out = append(out, fb.Config{EveryWrite: true})
			continue
		}
		var f float64
		if _, err := fmt.Sscanf(part, "%g", &f); err != nil {
			fmt.Fprintf(os.Stderr, "ignoring unparseable fps %q\n", part)
			continue
		}
		out = append(out, fb.Config{FPS: f})
	}
	return out
}

func writeTable(b *strings.Builder, rows []*fb.Metrics) {
	fmt.Fprintf(b, "| frame rate | frames | RAW B | POSITIONAL B | POS /RAW | SCROLL-AWARE B | SCROLL /RAW | OMITTED B | POS+OMITTED B | /RAW | SCROLL+OMITTED B | /RAW | scroll ops | omitted rows | retained B | retained rows |\n")
	fmt.Fprintf(b, "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n")
	for _, m := range rows {
		fmt.Fprintf(b, "| %s | %d | %d | %d | %s | %d | %s | %d | %d | %s | %d | %s | %d | %d | %d | %d |\n",
			m.Label, m.Frames, m.Raw,
			m.Positional, ratio(m.Positional, m.Raw),
			m.ScrollAware, ratio(m.ScrollAware, m.Raw),
			m.Omitted,
			m.Positional+m.Omitted, ratio(m.Positional+m.Omitted, m.Raw),
			m.ScrollAware+m.Omitted, ratio(m.ScrollAware+m.Omitted, m.Raw),
			m.ScrollOps, m.OmittedRows, m.OmittedRetained, m.OmittedRetainedRows)
	}
}

// writeHeroRates restates the hero table per second, which is the unit the
// design document's argument is written in (≈60 KB/s, ≈240 KB/s).
func writeHeroRates(b *strings.Builder, rows []*fb.Metrics) {
	fmt.Fprintf(b, "\n### hero, per second\n\n")
	fmt.Fprintf(b, "| frame rate | RAW B/s | POSITIONAL B/s | SCROLL-AWARE B/s | POS+OMITTED B/s | SCROLL+OMITTED B/s |\n|---|---|---|---|---|---|\n")
	for _, m := range rows {
		secs := float64(m.DurationMs) / 1000
		if secs <= 0 {
			continue
		}
		fmt.Fprintf(b, "| %s | %.0f | %.0f | %.0f | %.0f | %.0f |\n",
			m.Label, float64(m.Raw)/secs, float64(m.Positional)/secs, float64(m.ScrollAware)/secs,
			float64(m.Positional+m.Omitted)/secs, float64(m.ScrollAware+m.Omitted)/secs)
	}
}

func ratio(a, b int) string {
	if b == 0 {
		return "—"
	}
	return fmt.Sprintf("%.2f", float64(a)/float64(b))
}

// writeCompression is the separate note the report is asked for: what a
// deflate layer would do to each stream. It is measured rather than asserted,
// and it is deliberately NOT part of the accounting above. It is measured at
// the frame rate the product would ship, 60 fps, whatever sweep the run used.
func writeCompression(b *strings.Builder, caps []*fb.Capture) {
	cfg := fb.Config{FPS: 60}
	fmt.Fprintf(b, "\n## Compression, measured separately\n\n")
	fmt.Fprintf(b, "Deflate at its default level over each whole stream, at %s. Not part of the accounting above, and here because of two follow-up questions: whether the positional encoder's cost is an artefact of an uncompressed stream, and whether compression closes the gap between raw output and frames. A deflated byte is a different claim from the one §7 is arguing about, so this table decides neither; it is reported so nobody has to guess.\n\n", cfg.Label())
	fmt.Fprintf(b, "| capture | RAW B | RAW deflated | POSITIONAL deflated | SCROLL-AWARE deflated | deflated POS /RAW | deflated SCROLL /RAW |\n")
	fmt.Fprintf(b, "|---|---|---|---|---|---|---|\n")
	for _, c := range caps {
		raw, pos, scroll := fb.Streams(c, cfg)
		dr, dp, ds := deflated(raw), deflated(pos), deflated(scroll)
		fmt.Fprintf(b, "| %s | %d | %d (%s) | %d (%s) | %d (%s) | %s | %s |\n",
			c.Name, len(raw), dr, ratio(dr, len(raw)), dp, ratio(dp, len(raw)), ds, ratio(ds, len(raw)),
			ratio(dp, dr), ratio(ds, dr))
	}
}

func deflated(b []byte) int {
	var buf bytes.Buffer
	w, err := flate.NewWriter(&buf, flate.DefaultCompression)
	if err != nil {
		return 0
	}
	if _, err := w.Write(b); err != nil {
		return 0
	}
	if err := w.Close(); err != nil {
		return 0
	}
	return buf.Len()
}
