// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWSPort(): Promise<number>;

export interface UpdateInfo {
  Version: string;
  NotesURL: string;
}

export function CheckForUpdate(): Promise<UpdateInfo | null>;
export function ApplyUpdate(): Promise<void>;
export function ReportHealthy(): Promise<void>;
